// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfa5fXoDpEJuIK6697ViWveXEhMJ3gQ4s',
    appId: '1:596596194168:web:9c2be7435190849e38a68d',
    messagingSenderId: '596596194168',
    projectId: 'tls-service-51d66',
    authDomain: 'tls-service-51d66.firebaseapp.com',
    storageBucket: 'tls-service-51d66.appspot.com',
    measurementId: 'G-J60W479FDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7rmgGbj-B5T5QcVpqBh8LXy54CXnE-ew',
    appId: '1:596596194168:android:d9afe6a75d227c7638a68d',
    messagingSenderId: '596596194168',
    projectId: 'tls-service-51d66',
    storageBucket: 'tls-service-51d66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSMRtbT9l3RinihaZvQeRB4aRkrwIsdbU',
    appId: '1:596596194168:ios:a409f2ae4c400ca738a68d',
    messagingSenderId: '596596194168',
    projectId: 'tls-service-51d66',
    storageBucket: 'tls-service-51d66.appspot.com',
    iosBundleId: 'com.tlsservice.tls',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSMRtbT9l3RinihaZvQeRB4aRkrwIsdbU',
    appId: '1:596596194168:ios:3a5a4c59c27327d838a68d',
    messagingSenderId: '596596194168',
    projectId: 'tls-service-51d66',
    storageBucket: 'tls-service-51d66.appspot.com',
    iosBundleId: 'com.example.tls',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfa5fXoDpEJuIK6697ViWveXEhMJ3gQ4s',
    appId: '1:596596194168:web:ae3f6ec270d88b9e38a68d',
    messagingSenderId: '596596194168',
    projectId: 'tls-service-51d66',
    authDomain: 'tls-service-51d66.firebaseapp.com',
    storageBucket: 'tls-service-51d66.appspot.com',
    measurementId: 'G-Y707NZ0B7T',
  );
}
